CXX = g++
CXXFLAGS = -std=c++11 -Wall
OBJS = capitalize_vowels_main.cc capitalize_vowels.cc

capitalize_vowels: $(OBJS)
	g++ -o capitalize_vowels $(OBJS) 
clean: 
	rm -f capitalize_vowels
run:
	./capitalize_vowels
